apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysecret
  namespace: default
spec:
  encryptedData:
    username: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEQAxv0gJhkCOx8bF1P2nYgJ0m5K+PiTySYZZA9rO43cGDEQAxv0gJhkCOx8bF1P2nYgJ0m5
    password: BgCy4JKSWL+QjUzTaZZB0sP54dHEFRBy1gKilDPy9cG2Q3oZhK1n6L+QjUzTaZZB0sP54dHEFRBy1gKilDPy9cG2Q3oZhK1n6
  template:
    metadata:
      name: mysecret
      namespace: default
    type: Opaque
